name: Release

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version number'
        required: true

jobs:
  build:
    name: Build release
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish single-file EXE
        run: |
          dotnet publish ./GOMPPDMLoader/GOMPPDMLoader.csproj `
            --configuration Release `
            --runtime win-x64 `
            --self-contained true `
            /p:PublishSingleFile=true `
            /p:IncludeNativeLibrariesForSelfExtract=true `
            /p:PublishTrimmed=false `
            /p:Version=${{ github.event.inputs.versionNumber }}

      - name: Upload published EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: GOMPPDMLoader-${{ github.event.inputs.versionNumber }}
          path: ./GOMPPDMLoader/bin/Release/net8.0/win-x64/publish/
