name: Release

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version number'
        required: true

jobs:
  build:
    name: Build release
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ./GOMPPDMLoader/GOMPPDMLoader.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o publish

      - name: Upload GOMPPDMLoader build artifact
        uses: actions/upload-artifact@v4
        with:
          name: GOMPPDMLoader
          path: publish/GOMPPDMLoader.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.versionNumber }}
          name: v${{ github.event.inputs.versionNumber }}
          files: publish/GOMPPDMLoader.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
